services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    container_name: libsql
    ports:
      - "8080:8080"
    volumes:
      - libsql_data:/var/lib/libsql

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  libsql_data:
  redis_data: